/**
 * pdfReports.ts
 * Client-side PDF generation using jsPDF + jspdf-autotable.
 * Three exports: student report card, teacher report, admin report.
 */

import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/* ── shared helpers ──────────────────────────────────────────── */

const ACCENT  = [124, 58, 237] as [number, number, number];  // purple
const SUCCESS = [80, 205, 137] as [number, number, number];
const DANGER  = [241, 65, 108] as [number, number, number];
const INFO    = [0, 158, 247]  as [number, number, number];
const MUTED   = [150, 150, 160] as [number, number, number];

function gradeColor(grade: string): [number, number, number] {
  const map: Record<string, [number, number, number]> = {
    O: SUCCESS, E: INFO, A: [167, 139, 250],
    B: [255, 199, 0], C: [255, 199, 0], D: [255, 199, 0], F: DANGER,
  };
  return map[grade] || MUTED;
}

function addHeader(doc: jsPDF, title: string, subtitle: string, date: string) {
  // Purple header bar
  doc.setFillColor(...ACCENT);
  doc.rect(0, 0, 210, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('ia Academy', 12, 11);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Academic Management System', 12, 18);

  // Right side
  doc.setFontSize(8);
  doc.text(date, 198, 18, { align: 'right' });

  // Title below header
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 12, 40);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...MUTED);
  doc.text(subtitle, 12, 48);

  return 56; // y cursor after header
}

function addFooter(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(
      `Page ${i} of ${pages}  ·  Generated by ia Academy AMS  ·  Confidential`,
      105, 290, { align: 'center' }
    );
    doc.setDrawColor(...MUTED);
    doc.line(12, 286, 198, 286);
  }
}

function infoRow(doc: jsPDF, label: string, value: string, x: number, y: number) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(label.toUpperCase(), x, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(30, 30, 30);
  doc.text(value, x, y + 5);
}

/* ── 1. Student Report Card ──────────────────────────────────── */

export function downloadStudentReport(
  user: { name: string; email: string },
  marks: any[],
) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const date = new Date().toLocaleDateString('en-IN', {
    day: '2-digit', month: 'long', year: 'numeric',
  });

  let y = addHeader(doc, 'Student Report Card', 'Academic Performance Summary', date);

  // Student info block
  doc.setFillColor(248, 246, 255);
  doc.roundedRect(12, y, 186, 24, 3, 3, 'F');
  infoRow(doc, 'Student Name', user.name,  18, y + 7);
  infoRow(doc, 'Email',        user.email, 90, y + 7);
  infoRow(doc, 'Report Date',  date,       160, y + 7);
  y += 32;

  // Summary stats
  const avg    = marks.length ? marks.reduce((s, m) => s + (m.total || 0), 0) / marks.length : 0;
  const passed = marks.filter(m => m.grade !== 'F').length;
  const failed = marks.length - passed;

  const stats = [
    { label: 'Subjects', value: marks.length.toString() },
    { label: 'Average Score', value: marks.length ? `${avg.toFixed(1)} / 100` : '—' },
    { label: 'Passed', value: passed.toString() },
    { label: 'Failed', value: failed.toString() },
  ];

  const sw = 186 / 4;
  stats.forEach((s, i) => {
    const sx = 12 + i * sw;
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(220, 215, 240);
    doc.roundedRect(sx, y, sw - 2, 18, 2, 2, 'FD');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.text(s.label, sx + (sw - 2) / 2, y + 6, { align: 'center' });
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(i === 3 && failed > 0 ? DANGER[0] : ACCENT[0],
                     i === 3 && failed > 0 ? DANGER[1] : ACCENT[1],
                     i === 3 && failed > 0 ? DANGER[2] : ACCENT[2]);
    doc.text(s.value, sx + (sw - 2) / 2, y + 14, { align: 'center' });
  });
  y += 26;

  // Results table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);
  doc.text('Subject-wise Results', 12, y);
  y += 4;

  const rows = marks.map(m => [
    m.assignment_id?.subject_id?.subject_name || '—',
    m.assignment_id?.teacher_id?.user_id?.name || '—',
    `Sem ${m.assignment_id?.semester || '—'}`,
    String(m.midsem ?? '—'),
    String(m.endsem ?? '—'),
    String(m.quiz ?? '—'),
    String(m.assignment ?? '—'),
    String(m.total ?? '—'),
    m.grade || '—',
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Subject', 'Teacher', 'Sem', 'Mid', 'End', 'Quiz', 'Assg', 'Total', 'Grade']],
    body: rows,
    theme: 'grid',
    headStyles: { fillColor: ACCENT, textColor: 255, fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8, textColor: [30, 30, 30] },
    columnStyles: {
      0: { cellWidth: 40, fontStyle: 'bold' },
      8: { cellWidth: 14, halign: 'center', fontStyle: 'bold' },
    },
    didDrawCell: (data) => {
      // Color grade cell
      if (data.section === 'body' && data.column.index === 8) {
        const grade = String(data.cell.raw);
        const [r, g, b] = gradeColor(grade);
        doc.setTextColor(r, g, b);
      }
    },
    alternateRowStyles: { fillColor: [250, 248, 255] },
    margin: { left: 12, right: 12 },
  });

  addFooter(doc);
  doc.save(`${user.name.replace(/\s+/g, '_')}_Report_Card.pdf`);
}

/* ── 2. Teacher Performance Report ──────────────────────────── */

export function downloadTeacherReport(
  teacher: { name: string; email: string },
  analyses: any[],
) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const date = new Date().toLocaleDateString('en-IN', {
    day: '2-digit', month: 'long', year: 'numeric',
  });

  let y = addHeader(doc, 'Teacher Performance Report', 'Class Analytics Summary', date);

  doc.setFillColor(248, 246, 255);
  doc.roundedRect(12, y, 186, 24, 3, 3, 'F');
  infoRow(doc, 'Teacher Name', teacher.name,  18, y + 7);
  infoRow(doc, 'Email',        teacher.email, 90, y + 7);
  infoRow(doc, 'Total Classes', `${analyses.length} assignment${analyses.length !== 1 ? 's' : ''}`, 160, y + 7);
  y += 32;

  // Overall summary
  const totalStudents  = analyses.reduce((s, a) => s + (a.total_students || 0), 0);
  const overallAvg     = analyses.length
    ? analyses.reduce((s, a) => s + (a.average_total || 0), 0) / analyses.length
    : 0;
  const totalFailed    = analyses.reduce((s, a) => s + (a.failed || 0), 0);
  const totalOutstand  = analyses.reduce((s, a) => s + (a.above_90 || 0), 0);

  const stats = [
    { label: 'Total Students', value: totalStudents.toString() },
    { label: 'Overall Avg',    value: `${overallAvg.toFixed(1)}%` },
    { label: 'Outstanding',    value: totalOutstand.toString() },
    { label: 'Failed',         value: totalFailed.toString() },
  ];

  const sw = 186 / 4;
  stats.forEach((s, i) => {
    const sx = 12 + i * sw;
    doc.setFillColor(255, 255, 255);
    doc.setDrawColor(220, 215, 240);
    doc.roundedRect(sx, y, sw - 2, 18, 2, 2, 'FD');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.text(s.label, sx + (sw - 2) / 2, y + 6, { align: 'center' });
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    const color = i === 3 && totalFailed > 0 ? DANGER : i === 2 ? SUCCESS : ACCENT;
    doc.setTextColor(...color);
    doc.text(s.value, sx + (sw - 2) / 2, y + 14, { align: 'center' });
  });
  y += 26;

  // Per-assignment table
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(30, 30, 30);
  doc.text('Assignment-wise Breakdown', 12, y);
  y += 4;

  const rows = analyses.map(a => [
    a.subject || '—',
    a.batch   || '—',
    `Sem ${a.semester}`,
    String(a.total_students || 0),
    `${(a.average_total || 0).toFixed(1)}`,
    String(a.above_90 || 0),
    String(a.between_50_90 || 0),
    String(a.failed || 0),
    // Grade distribution compact
    Object.entries(a.grade_distribution || {})
      .filter(([, v]) => Number(v) > 0)
      .map(([g, v]) => `${g}:${v}`)
      .join('  '),
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Subject', 'Batch', 'Sem', 'Students', 'Avg', '>90', '50–90', 'Failed', 'Grade Split']],
    body: rows,
    theme: 'grid',
    headStyles: { fillColor: ACCENT, textColor: 255, fontSize: 8, fontStyle: 'bold' },
    bodyStyles: { fontSize: 8, textColor: [30, 30, 30] },
    columnStyles: {
      0: { cellWidth: 35, fontStyle: 'bold' },
      8: { cellWidth: 42, fontSize: 7 },
    },
    alternateRowStyles: { fillColor: [250, 248, 255] },
    margin: { left: 12, right: 12 },
  });

  addFooter(doc);
  doc.save(`${teacher.name.replace(/\s+/g, '_')}_Performance_Report.pdf`);
}

/* ── 3. Admin Performance Report ────────────────────────────── */

export function downloadAdminReport(
  analyses: any[],
  filters: { branch?: string; year?: string; subject?: string },
) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4', orientation: 'landscape' });
  const date = new Date().toLocaleDateString('en-IN', {
    day: '2-digit', month: 'long', year: 'numeric',
  });

  const filterLabel = [
    filters.branch  ? `Branch: ${filters.branch}`   : '',
    filters.year    ? `Batch: ${filters.year}`       : '',
    filters.subject ? `Subject: ${filters.subject}`  : '',
  ].filter(Boolean).join('  ·  ') || 'All Branches & Batches';

  // Landscape header
  let y = 6;
  doc.setFillColor(...ACCENT);
  doc.rect(0, 0, 297, 22, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('ia Academy — Admin Performance Report', 12, 10);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text(filterLabel, 12, 17);
  doc.text(date, 285, 17, { align: 'right' });
  y = 30;

  // Summary row
  const totalStudents  = analyses.reduce((s, a) => s + (a.total_students || 0), 0);
  const overallAvg     = analyses.length
    ? analyses.reduce((s, a) => s + (a.average_total || 0) * (a.total_students || 0), 0) / (totalStudents || 1)
    : 0;
  const totalFailed    = analyses.reduce((s, a) => s + (a.failed || 0), 0);
  const totalAbove90   = analyses.reduce((s, a) => s + (a.above_90 || 0), 0);

  const stats = [
    { label: 'Records',       value: analyses.length.toString() },
    { label: 'Total Students', value: totalStudents.toString() },
    { label: 'Overall Avg',   value: `${overallAvg.toFixed(1)}%` },
    { label: 'Outstanding',   value: totalAbove90.toString() },
    { label: 'Failed',        value: totalFailed.toString() },
    { label: 'Pass Rate',     value: totalStudents > 0
      ? `${(((totalStudents - totalFailed) / totalStudents) * 100).toFixed(1)}%`
      : '—' },
  ];

  const sw = 273 / 6;
  stats.forEach((s, i) => {
    const sx = 12 + i * sw;
    doc.setFillColor(248, 246, 255);
    doc.roundedRect(sx, y, sw - 2, 16, 2, 2, 'F');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(6);
    doc.setTextColor(...MUTED);
    doc.text(s.label, sx + (sw - 2) / 2, y + 5, { align: 'center' });
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    const color = i === 4 && totalFailed > 0 ? DANGER : i === 3 ? SUCCESS : ACCENT;
    doc.setTextColor(...color);
    doc.text(s.value, sx + (sw - 2) / 2, y + 13, { align: 'center' });
  });
  y += 24;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(30, 30, 30);
  doc.text('Detailed Performance Data', 12, y);
  y += 3;

  const rows = analyses.map(a => [
    a.branch_name || '—',
    `${a.start_year || ''}–${a.graduation_year || ''}`,
    `Sem ${a.semester}`,
    a.subject  || '—',
    a.teacher  || '—',
    String(a.total_students || 0),
    `${(a.average_total || 0).toFixed(1)}`,
    String(a.above_90 || 0),
    String(a.between_50_90 || 0),
    String(a.failed || 0),
    totalStudents > 0
      ? `${(((a.total_students - a.failed) / (a.total_students || 1)) * 100).toFixed(0)}%`
      : '—',
    Object.entries(a.grade_distribution || {})
      .filter(([, v]) => Number(v) > 0)
      .map(([g, v]) => `${g}:${v}`)
      .join(' '),
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Branch', 'Batch', 'Sem', 'Subject', 'Teacher', 'Students', 'Avg', '>90', '50–90', 'Failed', 'Pass%', 'Grades']],
    body: rows,
    theme: 'grid',
    headStyles: { fillColor: ACCENT, textColor: 255, fontSize: 7.5, fontStyle: 'bold' },
    bodyStyles: { fontSize: 7, textColor: [30, 30, 30] },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 28 },
      3: { cellWidth: 30 },
      4: { cellWidth: 28 },
      11: { cellWidth: 30, fontSize: 6.5 },
    },
    alternateRowStyles: { fillColor: [250, 248, 255] },
    margin: { left: 12, right: 12 },
  });

  // Footer
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(...MUTED);
    doc.text(
      `Page ${i} of ${pages}  ·  ia Academy AMS  ·  Confidential`,
      148.5, 205, { align: 'center' }
    );
  }

  const fname = `Admin_Performance_Report_${filters.branch || 'All'}_${date.replace(/ /g, '_')}.pdf`;
  doc.save(fname);
}
